<?php

namespace Effiana\MigrationBundle\Command;

use Doctrine\DBAL\DBALException;
use Effiana\MigrationBundle\Migration\Loader\MigrationsLoader;
use Effiana\MigrationBundle\Migration\MigrationExecutor;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Effiana\MigrationBundle\Migration\MigrationExecutorWithNameGenerator;

/**
 * Class LoadMigrationsCommand
 * @package Effiana\MigrationBundle\Command
 */
class LoadMigrationsCommand extends Command
{
    /**
     * @var MigrationExecutorWithNameGenerator
     */
    private $executorWithNameGenerator;
    /**
     * @var MigrationsLoader
     */
    private $migrationsLoader;
    /**
     * @var LoggerInterface
     */
    private $logger;

    public function __construct(MigrationExecutorWithNameGenerator $executorWithNameGenerator,
                                MigrationsLoader $migrationsLoader, LoggerInterface $logger)
    {
        parent::__construct();
        $this->executorWithNameGenerator = $executorWithNameGenerator;
        $this->migrationsLoader = $migrationsLoader;
        $this->logger = $logger;
    }

    /**
     * @inheritdoc
     */
    protected function configure(): void
    {
        $this->setName('effiana:migration:load')
            ->setDescription('Execute migration scripts.')
            ->addOption(
                'force',
                null,
                InputOption::VALUE_NONE,
                'Causes the generated by migrations SQL statements to be physically executed against your database.'
            )
            ->addOption(
                'dry-run',
                null,
                InputOption::VALUE_NONE,
                'Outputs list of migrations without apply them.'
            )
            ->addOption(
                'show-queries',
                null,
                InputOption::VALUE_NONE,
                'Outputs list of database queries for each migration file.'
            )
            ->addOption(
                'bundles',
                null,
                InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL,
                'A list of bundles to load data from. If option is not set, migrations will be taken from all bundles.'
            )
            ->addOption(
                'exclude',
                null,
                InputOption::VALUE_IS_ARRAY | InputOption::VALUE_OPTIONAL,
                'A list of bundle names which migrations should be skipped.'
            )
            ->addOption(
                'timeout',
                null,
                InputOption::VALUE_OPTIONAL,
                'Timeout for child command execution',
                10
            );
    }

    /**
     * @inheritdoc
     * @param InputInterface $input
     * @param OutputInterface $output
     * @throws DBALException
     * @throws \ReflectionException
     */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $force = $input->getOption('force');
        $dryRun = $input->getOption('dry-run');

        if ($force || $dryRun) {
            $output->writeln($dryRun ? 'List of migrations:' : 'Process migrations...');

            $migrationLoader = $this->getMigrationLoader($input);
            $migrations      = $migrationLoader->getMigrations();
            if (!empty($migrations)) {
                if ($input->getOption('dry-run') && !$input->getOption('show-queries')) {
                    foreach ($migrations as $item) {
                        $output->writeln(sprintf('  <comment>> %s</comment>', get_class($item->getMigration())));
                    }
                } else {
                    $executor    = $this->getMigrationExecutor($input);
                    $executor->setLogger($this->logger);
                    $executor->executeUp($migrations, $input->getOption('dry-run'));
                }
            }
        } else {
            $output->writeln(
                '<comment>ATTENTION</comment>: Database backup is highly recommended before executing this command.'
            );
            $output->writeln('');
            $output->writeln('To force execution run command with <info>--force</info> option:');
            $output->writeln(sprintf('    <info>%s --force</info>', $this->getName()));
        }

        return 0;
    }

    /**
     * @param InputInterface $input
     * @return MigrationsLoader
     */
    protected function getMigrationLoader(InputInterface $input): MigrationsLoader
    {
        $bundles         = $input->getOption('bundles');
        if (!empty($bundles)) {
            $this->migrationsLoader->setBundles($bundles);
        }
        $excludeBundles = $input->getOption('exclude');
        if (!empty($excludeBundles)) {
            $this->migrationsLoader->setExcludeBundles($excludeBundles);
        }

        return $this->migrationsLoader;
    }

    /**
     * @param InputInterface $input
     * @return MigrationExecutor
     */
    protected function getMigrationExecutor(InputInterface $input): MigrationExecutor
    {
        return $this->executorWithNameGenerator;
    }
}
