services:
    Effiana\MigrationBundle\Command\DumpMigrationsCommand:
        autowire: true
        autoconfigure: true
        tags:
            - { name: console.command }

    Effiana\MigrationBundle\Command\LoadDataFixturesCommand:
        autowire: true
        autoconfigure: true
        tags:
            - { name: console.command }

    Effiana\MigrationBundle\Command\LoadMigrationsCommand:
        autowire: true
        autoconfigure: true
        tags:
            - { name: console.command }
