services:
    Effiana\MigrationBundle\Command\DumpMigrationsCommand:
        public: false
        class: Effiana\MigrationBundle\Command\DumpMigrationsCommand
        tags:
            - { name: console.command }

    Effiana\MigrationBundle\Command\LoadDataFixturesCommand:
        public: false
        arguments:
            - '@kernel'
            - '@effiana_migration.data_fixtures.loader'
            - '@effiana_migration.data_fixtures.executor'
            - '@effiana_migration.locator.fixture_path_locator'
        class: Effiana\MigrationBundle\Command\LoadDataFixturesCommand
        tags:
            - { name: console.command }

    Effiana\MigrationBundle\Command\LoadMigrationsCommand:
        public: false
        class: Effiana\MigrationBundle\Command\LoadMigrationsCommand
        tags:
            - { name: console.command }
