services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means

    Effiana\MigrationBundle\Tools\DbIdentifierNameGenerator: ~

    Effiana\MigrationBundle\Container\MigrationContainer:
        public: false
        arguments:
            - '@?parameter_bag'
            - '@service_container'
            - !service
                class: Symfony\Component\DependencyInjection\ServiceLocator
                arguments: [[]]
    Effiana\MigrationBundle\Migration\Loader\DataFixturesLoader:
        public: true

    Effiana\MigrationBundle\Migration\DataFixturesExecutorInterface:
        class: Effiana\MigrationBundle\Migration\DataFixturesExecutor

    Effiana\MigrationBundle\Migration\Loader\MigrationsLoader:
        public: true

    Effiana\MigrationBundle\Migration\MigrationQueryExecutor: ~

    Effiana\MigrationBundle\Migration\MigrationExecutorWithNameGenerator:
        public: true
        calls:
            - [setExtensionManager, ['@Effiana\MigrationBundle\Migration\MigrationExtensionManager']]
            - [setNameGenerator, ['@Effiana\MigrationBundle\Tools\DbIdentifierNameGenerator']]

    Effiana\MigrationBundle\EventListener\PreUpMigrationListener:
        tags:
            - { name: kernel.event_listener, event: effiana_migration.pre_up, method: onPreUp }

    Effiana\MigrationBundle\Migration\MigrationExtensionManager: ~

    Effiana\MigrationBundle\Migration\Extension\RenameExtension:
        tags:
            - { name: effiana_migration.extension, extension_name: rename }

    Effiana\MigrationBundle\Migration\Extension\DataStorageExtension:
        tags:
            - { name: effiana_migration.extension, extension_name: data_store }

    Effiana\MigrationBundle\Tools\SchemaDumper:
        lazy: true

    Effiana\MigrationBundle\Twig\SchemaDumperExtension:
        public: false
        tags:
            - { name: twig.extension }

    Effiana\MigrationBundle\EventListener\ConsoleCommandListener:
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

    Effiana\MigrationBundle\Locator\FixturePathLocatorInterface:
        class: Effiana\MigrationBundle\Locator\FixturePathLocator