<?php

//@codingStandardsIgnoreFile
// This class is created based on Doctrine\DBAL\Schema\SchemaDiff,
// in order to disable automatic rename of autogenerated indices
// as since v2.5.1 schema update force index renaming which is very heavy operation
// for existing database and require a lot of effort from developers
// to prepare proper migrations as well.
// For details see _toSql and disableIndicesRenaming methods.
// {@see \Effiana\MigrationBundle\EventListener\ConsoleCommandListener::onConsoleCommand}
// @todo because of this change we have to watch changes in Doctrine\DBAL\Schema\SchemaDiff

namespace Effiana\MigrationBundle\Migration\Schema;

use Doctrine\DBAL\DBALException;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Schema\ForeignKeyConstraint;
use Doctrine\DBAL\Schema\Sequence;
use Doctrine\DBAL\Schema\TableDiff;

class SchemaDiff
{
    /**
     * @var \Doctrine\DBAL\Schema\Schema
     */
    public $fromSchema;

    /**
     * All added namespaces.
     *
     * @var string[]
     */
    public $newNamespaces = [];

    /**
     * All removed namespaces.
     *
     * @var string[]
     */
    public $removedNamespaces = [];

    /**
     * All added tables.
     *
     * @var \Doctrine\DBAL\Schema\Table[]
     */
    public $newTables = [];

    /**
     * All changed tables.
     *
     * @var TableDiff[]
     */
    public $changedTables = [];

    /**
     * All removed tables.
     *
     * @var \Doctrine\DBAL\Schema\Table[]
     */
    public $removedTables = [];

    /**
     * @var Sequence[]
     */
    public $newSequences = [];

    /**
     * @var Sequence[]
     */
    public $changedSequences = [];

    /**
     * @var Sequence[]
     */
    public $removedSequences = [];

    /**
     * @var ForeignKeyConstraint[]
     */
    public $orphanedForeignKeys = [];

    /**
     * Constructs an SchemaDiff object.
     *
     * @param \Doctrine\DBAL\Schema\Table[]     $newTables
     * @param TableDiff[] $changedTables
     * @param \Doctrine\DBAL\Schema\Table[]     $removedTables
     * @param \Doctrine\DBAL\Schema\Schema|null $fromSchema
     */
    public function __construct($newTables = [], $changedTables = [], $removedTables = [], $fromSchema = null)
    {
        $this->newTables     = $newTables;
        $this->changedTables = $changedTables;
        $this->removedTables = $removedTables;
        $this->fromSchema    = $fromSchema;
    }

    /**
     * The to save sql mode ensures that the following things don't happen:
     *
     * 1. Tables are deleted
     * 2. Sequences are deleted
     * 3. Foreign Keys which reference tables that would otherwise be deleted.
     *
     * This way it is ensured that assets are deleted which might not be relevant to the metadata schema at all.
     *
     * @param AbstractPlatform $platform
     *
     * @return array
     * @throws DBALException
     */
    public function toSaveSql(AbstractPlatform $platform): array
    {
        return $this->_toSql($platform, true);
    }

    /**
     * @param AbstractPlatform $platform
     *
     * @return array
     * @throws DBALException
     */
    public function toSql(AbstractPlatform $platform): array
    {
        return $this->_toSql($platform, false);
    }

    /**
     * @SuppressWarnings(PHPMD.NPathComplexity)
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     *
     * @param AbstractPlatform $platform
     * @param boolean $saveMode
     *
     * @return array
     * @throws DBALException
     */
    protected function _toSql(AbstractPlatform $platform, $saveMode = false): array
    {
        // Disable renaming of indices
        $this->disableIndicesRenaming();

        $sql = [];

        if ($platform->supportsSchemas()) {
            foreach ($this->newNamespaces as $newNamespace) {
                $sql[] = $platform->getCreateSchemaSQL($newNamespace);
            }
        }

        if ($saveMode === false && $platform->supportsForeignKeyConstraints()) {
            foreach ($this->orphanedForeignKeys as $orphanedForeignKey) {
                $sql[] = $platform->getDropForeignKeySQL($orphanedForeignKey, $orphanedForeignKey->getLocalTableName());
            }
        }

        if ($platform->supportsSequences() === true) {
            foreach ($this->changedSequences as $sequence) {
                $sql[] = $platform->getAlterSequenceSQL($sequence);
            }

            if ($saveMode === false) {
                foreach ($this->removedSequences as $sequence) {
                    $sql[] = $platform->getDropSequenceSQL($sequence);
                }
            }

            foreach ($this->newSequences as $sequence) {
                $sql[] = $platform->getCreateSequenceSQL($sequence);
            }
        }

        $foreignKeySql = [];
        $tableSql = [];
        foreach ($this->newTables as $table) {
            $tableSql[] = $platform->getCreateTableSQL($table, AbstractPlatform::CREATE_INDEXES);
            if ($platform->supportsForeignKeyConstraints()) {
                foreach ($table->getForeignKeys() as $foreignKey) {
                    $foreignKeySql[] = $platform->getCreateForeignKeySQL($foreignKey, $table);
                }
            }
        }
        $sql = array_merge($sql, array_merge(...$tableSql));
        $sql = array_merge($sql, $foreignKeySql);

        if ($saveMode === false) {
            foreach ($this->removedTables as $table) {
                $sql[] = $platform->getDropTableSQL($table);
            }
        }
        $tableSql = [];
        foreach ($this->changedTables as $tableDiff) {
            $tableSql[] = $platform->getAlterTableSQL($tableDiff);
        }
        $sql = array_merge($sql, array_merge(...$tableSql));

        return $sql;
    }

    protected function disableIndicesRenaming(): void
    {
        foreach ($this->changedTables as $table) {
            $table->renamedIndexes = [];
        }
    }
}
